FLASK_APP = "run"
FLASK_ENV = "development"


FLASK_MYSQL_HOST = "localhost"
FLASK_MYSQL_PORT = 3306
FLASK_MYSQL_USER = "root"
FLASK_MYSQL_PASSWORD = "123456"

FLASK_REDIS_HOST = "localhost"
FLASK_REDIS_PORT =  6379
FLASK_REDIS_PASSWORD = "123456"